from django.urls import path

from .views import (
    AdminFeeCollectionView,
    AdminFeeDetailView,
    FeePaymentCollectionView,
    FeePaymentCallbackView,
    FeeStatementView,
    FeePaymentReceiptPdfView,
    AdminActivityView,
    AdminClassCollectionView,
    AdminClassDetailView,
    AdminSchoolClassListView,
    AdminStudentListView,
    AdminOverviewView,
    AdminStatsView,
    AdminUserCollectionView,
    AdminUserDetailView,
    AttendanceContextView,
    AttendanceRecordCollectionView,
    AttendanceRecordDetailView,
    ClassRankingView,
    DashboardSummaryView,
    MarkEntryContextView,
    MarkEntryDetailView,
    MarkEntryView,
    TeacherTimetableExportView,
    TeacherTimetableView,
    AssignmentCollectionView,
    AssignmentDetailView,
    AssignmentMaterialCollectionView,
    AssignmentMaterialDetailView,
    AssignmentSubmissionsCollectionView,
    AssignmentSubmissionDetailView,
)


urlpatterns = [
    path('<str:role>/summary/', DashboardSummaryView.as_view(), name='dashboard-summary'),
    path('admin/overview/', AdminOverviewView.as_view(), name='admin-overview'),
    path('admin/stats/', AdminStatsView.as_view(), name='admin-stats'),
    path('admin/activity/', AdminActivityView.as_view(), name='admin-activity'),
    path('admin/classes/list/', AdminSchoolClassListView.as_view(), name='admin-classes-list'),
    path('admin/students/', AdminStudentListView.as_view(), name='admin-students-list'),
    path('admin/classes/', AdminClassCollectionView.as_view(), name='admin-classes'),
    path('admin/classes/<str:class_id>/', AdminClassDetailView.as_view(), name='admin-class-detail'),
    path('admin/users/', AdminUserCollectionView.as_view(), name='admin-users'),
    path('admin/users/<str:user_id>/', AdminUserDetailView.as_view(), name='admin-user-detail'),
    path('admin/fees/', AdminFeeCollectionView.as_view(), name='admin-fees'),
    path('admin/fees/<str:fee_id>/', AdminFeeDetailView.as_view(), name='admin-fee-detail'),
    path('fees/payments/', FeePaymentCollectionView.as_view(), name='fee-payments'),
    path('fees/payments/callback/', FeePaymentCallbackView.as_view(), name='fee-payment-callback'),
    path('fees/statements/', FeeStatementView.as_view(), name='fee-statements'),
    path('fees/payments/<str:payment_id>/receipt/', FeePaymentReceiptPdfView.as_view(), name='fee-payment-receipt'),
    path('marks/context/', MarkEntryContextView.as_view(), name='mark-entry-context'),
    path('marks/', MarkEntryView.as_view(), name='mark-entry'),
    path('marks/<str:mark_id>/', MarkEntryDetailView.as_view(), name='mark-entry-detail'),
    path('attendance/context/', AttendanceContextView.as_view(), name='attendance-context'),
    path('attendance/records/', AttendanceRecordCollectionView.as_view(), name='attendance-records'),
    path('attendance/records/<str:record_id>/', AttendanceRecordDetailView.as_view(), name='attendance-record-detail'),
    path('timetable/', TeacherTimetableView.as_view(), name='teacher-timetable'),
    path('timetable/<str:entry_id>/', TeacherTimetableView.as_view(), name='teacher-timetable-detail'),
    path('timetable/export/', TeacherTimetableExportView.as_view(), name='teacher-timetable-export'),
    path('assignments/', AssignmentCollectionView.as_view(), name='assignment-collection'),
    path('assignments/<str:assignment_id>/', AssignmentDetailView.as_view(), name='assignment-detail'),
    path('assignments/materials/', AssignmentMaterialCollectionView.as_view(), name='assignment-materials'),
    path('assignments/materials/<str:material_id>/', AssignmentMaterialDetailView.as_view(), name='assignment-material-detail'),
    path('assignments/submissions/', AssignmentSubmissionsCollectionView.as_view(), name='assignment-submissions'),
    path('assignments/submissions/<str:submission_id>/', AssignmentSubmissionDetailView.as_view(), name='assignment-submission-detail'),
    path('rankings/', ClassRankingView.as_view(), name='class-rankings'),
]
